### ISSUE TITLE
[BUG] HEATFS incorrect penetration readout/shell underperformance/improper jet spawning

### ISSUE THREAD

**Issue by reggreggregg** [Stooberton/ACF-3#146]
**Description:**
HEATFS (only HEATFS, HEAT, and GLATGM perform fine) has incorrect penetration readout in the menu and on the crates on the dev branch after the menu update- its performance seems to have deteriorated from the pre-menu dev branch (105mm HEATFS can't penetrate 200mm), and the shaped charge seems to spawn behind the gun, leading to vehicles damaging themselves as well.

**Reproducing:**
Creating any HEATFS round with the new menu will yield interesting results for the round penetration, with the 105mm smoothbore readout easily reaching thousands of millimeters of penetration.
Using an existing vehicle with HEATFS or setting up a test stand with a prop directly behind a gun will lead to the jet spawning seemingly behind the gun after hitting a target, leading to its target and the prop behind it taking damage.

**Screenshots/Videos:**
105mm Smoothbore HEATFS:
![image](https://user-images.githubusercontent.com/48999479/99852236-344b7e80-2b46-11eb-8578-15b433695969.png)
![image](https://user-images.githubusercontent.com/48999479/99852266-44635e00-2b46-11eb-8d8d-378508c1f35d.png)
140mm Smoothbore HEATFS:
![image](https://user-images.githubusercontent.com/48999479/99852298-56450100-2b46-11eb-864a-f1e11bd60934.png)
![image](https://user-images.githubusercontent.com/48999479/99852337-6957d100-2b46-11eb-947c-3812fe428647.png)
HEAT/HEATFS performance demonstration:
https://youtu.be/ZZo-E4aQ4qo
Jet spawning behind breech demonstration:
https://youtu.be/q7sUPtbA020
https://youtu.be/QwsLoRS5j-w
Dupe file for test stand:
[heat test_002.txt](https://github.com/Stooberton/ACF-3/files/5576473/heat.test_002.txt)

**Comment by TwistedTail** [comment]
HEATFS, and all other HEAT-based munitions since they all shared the affected bit of code, firing back and being unable to penetrate anything has been fixed on ac7b08b, it was a fault on the ballistic code that, for whatever reason, decided to send the projectile in the opposite direction.
HEATFS showing insane penetration values has been fixed on 464f2be and b72688a (my bad on the second one). It was faulty code from a moment when I decided to switch the bullet's calibers from centimeters to millimeters, which was eventually scrapped and reverted.
