### ISSUE TITLE
[SUGGESTION] Add checkboxes to enable/disable aspects of ACF

### ISSUE THREAD

**Issue by Stooberton** [Stooberton/ACF-3#156]
**Short Description**
Add checkboxes in the menu as well as hooks throughout ACF to disable functionality such as:
- Guns firing
- Guns making noise/smoke
- Whatever else we can think of (If you can think of something pls comment on this issue)

Also should probably should move the ACF build/protection mode to the ACF menu

**Comment by TwistedTail** [comment]
We could add [these settings from ACF Missiles](https://github.com/TwistedTail/ACF-3-Missiles/blob/master/lua/acf/base/sh_acfm_cvars.lua) to the menu, as I'm pretty sure people isn't aware of their existence. I've heard a bunch of people who asked for an option to prevent racks specifically from firing, so that could work independently from the `ACF.GunfireEnabled` global.

**Comment by Stooberton** [comment]
Added options for separate options for missiles and guns to fire as well as an option to toggle guns producing particles and sound in c58ddabe9fec41f3832d8c09a00a36769f62f3ee
