### ISSUE TITLE
[BUG] Clutch gearbox updating is still broken

### ISSUE THREAD

**Issue by TheMrFailz** [Stooberton/ACF-3#16]
Spawn a clutch type gearbox (as in, the thin thing that is literally just a clutch), then attempt to use the ACF tool to update said clutch's gear ratio, and get whacked with this fun error:

`[ERROR] addons/acf-3-master/lua/entities/acf_gearbox/init.lua:288: attempt to perform arithmetic on a string value
  1. Update - addons/acf-3-master/lua/entities/acf_gearbox/init.lua:288
   2. LeftClick - addons/acf-3-master/lua/weapons/gmod_tool/stools/acfmenu.lua:89
    3. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:240
`
I'm running ver. 660 (yes i know this is 1 update behind) but this has been an issue for at least a year with ACF2.

Other interesting info: Sometimes it actually still updates the gear ratio value, sometimes it does not. Usually not.

**Comment by TwistedTail** [comment]
Looking into it right now. Apparently gearboxes store the gear values as strings and since Lua seems to be able to interpret `"5" + "5"` as a valid mathematical operation, it means it's most likely receiving something it cannot translate as a number. Easiest fix would be just turning those values to number instead of letting it figure it out by itself.
