### ISSUE TITLE
[BUG] [Dev Branch] Menu doesn't display properly upon joining server after a map change

### ISSUE THREAD

**Issue by CheezusChrust** [Stooberton/ACF-3#168]
**Short Description**

Joined my server after changing maps, and the menu stopped displaying properly. Restarted my server completely and it's still happening.

**Branch and Version**

Latest version of dev.

**Console Error Logs (Optional)**

```
[acf-3] addons/acf-3/lua/acf/base/util/sh_util.lua:385: Tried to use a NULL physics object!
  1. GetAABB - [C]:-1
   2. GetModelData - addons/acf-3/lua/acf/base/util/sh_util.lua:385
    3. GetModelCenter - addons/acf-3/lua/acf/base/util/sh_util.lua:446
     4. UpdateModel - addons/acf-3/lua/vgui/acf_panel.lua:250
      5. AddModelPreview - addons/acf-3/lua/vgui/acf_panel.lua:289
       6. Action - addons/acf-3/lua/acf/client/menu_items/weapons_menu.lua:146
        7. OnNodeSelected - addons/acf-3/lua/acf/client/spawn_menu.lua:222
         8. OnNodeSelected - lua/vgui/dtree_node.lua:77
          9. OnNodeSelected - lua/vgui/dtree_node.lua:77
           10. OnNodeSelected - lua/vgui/dtree_node.lua:77
            11. SetSelectedItem - lua/vgui/dtree.lua:95
             12. OnNodeSelected - addons/acf-3/lua/acf/client/spawn_menu.lua:207
              13. OnNodeSelected - lua/vgui/dtree_node.lua:77
               14. OnNodeSelected - lua/vgui/dtree_node.lua:77
                15. SetSelectedItem - lua/vgui/dtree.lua:95
                 16. InternalDoClick - lua/vgui/dtree_node.lua:60
```

**Screenshots (Optional)**

![image](https://user-images.githubusercontent.com/21130637/111400496-d36c2700-869d-11eb-8439-4bb4cabcc40b.png)

**Comment by TwistedTail** [comment]
Been dealing with this problem for quite some time already. Clientside entities are really weird to say the least, and they come up with random errors and inconsistencies out of nowhere. On 3b2bb2a, decided to just make it spawn a `base_anim` on both realms instead of using `ents.CreateClientProp` as it apparently *might* not initialize physics on the entity. 

Since it's really inconsistent, I'm not gonna close this issue instantly in case someone happens to find this same issue after that patch.

**Comment by TwistedTail** [comment]
This bug seems to still happen in some cases. Gonna try to fiddle with it a little more to see if I can get any solutions, otherwise I'm just gonna make it so the model preview doesn't show anything if this fails, since it's an issue directly related to the engine itself (or at least that's what the error implies).
