### ISSUE TITLE
[BUG] (dev branch) Infinite loop in ACF_PenetrateMapEntity, lines 505 to 518

### ISSUE THREAD

**Issue by norrbotten** [Stooberton/ACF-3#172]
Pretty clear whats going on, this can probably just have some hard limit

[A trace of function calls](https://pastebin.com/c2VLRnQZ)

on latest dev branch

**Comment by TwistedTail** [comment]
Patched this issue on 71ee31f, bullets that could start an infinite loop when interacting map entities will be removed. It's not a definitive solution, in fact it's far from being an optimal one, so I won't close this issue and I suggest you to do the same.

I really don't like patching stuff instead of just fixing the actual problem, but I've been dealing with this issue for about 9 hours and I still can't find the root of it.
