### ISSUE TITLE
[BUG] Proper Clipping's physics mode not yet properly supported (armor values change upon being duped)

### ISSUE THREAD

**Issue by CheezusChrust** [Stooberton/ACF-3#173]
**Short Description**

When a prop is clipped using Proper Clipping with "physics" mode enabled, it doesn't properly retain armor when duped and respawned. Reproduce by armoring a prop that's been physically clipped and then duping and respawning it. The armor will have changed.

**Comment by TwistedTail** [comment]
I remember the best solution we came up with to solve this problem was not storing the mass of the entity but rather the armor value of it, since ACF does some convoluted shit when assigning the armor of an entity. Problem comes for the cases when people change the mass of an entity, we could probably just detect that and update the armor value automatically.

**Comment by TwistedTail** [comment]
Should be fixed on 91e6986.
