### ISSUE TITLE
[SUGGESTION] G Force Limit for Pods

### ISSUE THREAD

**Issue by almo-anth** [Stooberton/ACF-3#225]
ACF air combat is in dire need of a fix, players are able to slam into walls without suffering any meaningful repercussions, or pull sustained 10G+ maneuvers that would explode the brains of any normal pilot. So, a toggleable script enabled or disabled by a console command would be a cool fix, it could work by applying damage above a certain G limit to the player in the pod, and/or outright kill them if they exceed a certain threshold.

**Comment by Goodva** [comment]
this shouldn't be implemented into acf directly imo, but as a server plugin of sorts. now that i think about it, it can be implemented into acf directly like acf build/PvP modes.

**Comment by TwistedTail** [comment]
In my opinion, it's not something that should be included with ACF since it doesn't fit with the core idea of what it is: a framework of parts for combat vehicles.

However, @LiddulBOFH has made an addon exactly for this, you can find it [here](https://steamcommunity.com/sharedfiles/filedetails/?id=2649922889).
