### ISSUE TITLE
[BUG] Multi Gun Setups shooting themselves when moving.

### ISSUE THREAD

**Issue by bluemetaknight** [Stooberton/ACF-3#333]
Gun arrays seem to be hitting each other a lot more than usual. A 1x4 Light Autocannon array will consistently hit itself when shooting perpendicular to the vehicles direction of travel when traveling at any reasonable speed. This makes shooting while driving nigh impossible.

Branch: Git-master-6c55db9

![Wacky Guns](https://user-images.githubusercontent.com/26047711/203707472-6446c36f-e068-4c33-9514-c8fae17be0ea.png)

**Comment by bluemetaknight** [comment]
To Clarify, the guns' bounding boxes are not intersecting each other at any point, so they shouldn't be hitting each other. It seems like the bullet traces are being created slightly offset in the direction of travel, resulting in the traces self-intersecting with the next gun over.

**Comment by Goodva** [comment]
i also had this happen to me, however, the guns were hitting eachother even though the contraption will be not moving at all.

**Comment by TwistedTail** [comment]
It seems to be related to an offset on the `ENT:BarrelCheck` method that was, funnily enough, added just to prevent this kind of stuff 2 years ago. Whatever changed on these last two years, it seems like it's not needed anymore.

**Comment by Goodva** [comment]
Still happens to me, the server is running Git-master-988b1df. this is the setup. i really hope its not because the gun breech model collide with the other gun.
![изображение](https://user-images.githubusercontent.com/30363060/206857282-31e0dcd9-cf4d-4dd3-a61c-047930f6c818.png)
![изображение](https://user-images.githubusercontent.com/30363060/206857357-19531a96-b9d4-45c7-b627-6baa6d6c3c1b.png)

**Comment by TwistedTail** [comment]
That could be it, the barrel check won't filter out ACF entities (except for ACF Armor) in order to discourage entity clipping.
