### ISSUE TITLE
[BUG] Recieving periodic notifications that guns are illegal despite them still working and NOT being illegally parented.

### ISSUE THREAD

**Issue by ReichDoctor** [Stooberton/ACF-3#67]
Whenever I spawn a tank which was built on ACF-3 servers before the weldparent patch, it tells me that my guns are illegal. Yet, they still shoot and work like they are intended, because they are infact parented to a gate (capacitor model) which is parented to the gun. However I still get these annoying notifications that blast the Gmod error sound in my ear because they SAY that the guns are illegal, even though the server says they clearly aren't since they're still allowed to work.

**Comment by ReichDoctor** [comment]
Update: Only happens on ACF-3 Build-Only. On Build/Kill 1 and 2 it works fine.

**Comment by TwistedTail** [comment]
It was probably a problem with the install on the server. Reinstalled ACF entirely and tested all the Wire capacitor models and it seems to be working fine now. There was also [a small change on the legal check notifications](https://github.com/Stooberton/ACF-3/commit/37ef540440ab3c63497c1ec4120fdf7348c0d1e9), so they'll only appear when the disable reason changes instead of every time the legal checks are run.
