### ISSUE TITLE
[BUG] Engines need their ACF2 max output as default output

### ISSUE THREAD

**Issue by Amplar** [Stooberton/ACF-3#69]
Currently engines are stuck on their unfueled outputs. The balance of these engines was designed for the fuel boost as that's what most people used and any vehicles that rely on it are shafted (such as times when breaking traction is needed, such as spot turning.)

**Comment by Amplar** [comment]
Also forgot to mention it dicks over car builders.

**Comment by Stooberton** [comment]
This was intentional as vehicles are currently way too mobile. ACF balance is focused on AFVs. There are too many concessions that would be had to make cars viable and would hinder balance. Without vastly improved code operating behind the mobility components it's practically impossible.

Fuel being added as an optional "bonus" was a mistake and a weak attempt at balancing ACF. Now that fuel is required, consumption and weight can actually be used to influence tank design.

**Comment by TwistedTail** [comment]
Taking into account the mass ratio bug being more relevant than before thanks to the higher parenting capability on ACF-3, along with the lesser focus on mobility due to combat overhauling being a priority for the moment, it'd seem fair to appeal to the part of the community that prefers the automotive part of ACF over the combat part of it with this kind of changes.

I agree it was a mistake to *boost* fueled engines instead of hindering unfueled engines, so it'd be fair to just change some propierties on engines to fit these values by default.

**Comment by TwistedTail** [comment]
Should be addressed by 4b0b790. Only standalone electrics were an exception since they're already on a pretty good spot.
