### ISSUE TITLE
[BUG] Fuel consumption far too low

### ISSUE THREAD

**Issue by Amplar** [Stooberton/ACF-3#70]
Fuel consumption is currently nonexistent. There is no reason to not use the smallest fuel tank possible.
Exaggerated fuel consumption is needed for fuel tanks to occupy a realistic amount of space in a vehicle that's expected to roll about for several hundred kilometers.
Either restore fuel consumption or require a certain amount of fuel be present based on engine size.

**Comment by Stooberton** [comment]
This was addressed in 4305e8a3d7aba2d295bd05abf41dbca7f6f6bd63, with fuel consumption being increased by 27.8 times.

A tank built with a 120mm cannon, 30 rounds of ammo, an ACF pod, some autocannon ammo, a large V12 and transmissions consumes less than half the volume of an actual tank with the same specifications. Therefore, fuel consumption was increased to encourage about 1000L of fuel, under the assumption that tanks drive around for 5 to 15 minutes, in order to consume the remaining volume necessary to be "real tank" size.

I'll leave this issue open for further discussion as we'll have to see how this change works out.

**Comment by TwistedTail** [comment]
As a note for this, the increased fuel consumption will only apply to servers with `acf_gamemode` set to 2 (Competitive), since that's the whole nature of this change.
