### ISSUE TITLE
[BUG] [Dev Branch] Scalable ammo crates occasionally have incorrect hitbox on clientside

### ISSUE THREAD

**Issue by CheezusChrust** [Stooberton/ACF-3#81]
**Short Description**

When spawning a new scalable ammo crate (or pasting a dupe containing one), there's a chance for the hitbox on the clientside to be scaled or rotated (can't really tell which) incorrectly relative to the orientation it should be in according to the server.

**How to Reproduce (Optional)**

Spawn a scalable ammo crate with random dimensions and look at it near the edges with any tool. If the clientside hitbox looks fine, respawn it a few times.

**Screenshots (Optional)**

https://streamable.com/ap754m

![9VQHR3y](https://user-images.githubusercontent.com/21130637/86308725-f3c78480-bbe7-11ea-9d6e-f461f2e0cdef.jpg)

**Comment by TwistedTail** [comment]
This is a problem that I decided to keep as it, funnily enough, solves another, way more annoying problem.

The reason this happens is because of the client-side model is set to never move.
https://github.com/Stooberton/ACF-3/blob/956a6706f0bdc96f323ca0df19a409c149027cb9/lua/entities/base_scalable_box/cl_init.lua#L16
It actually just makes it so it never rotates, so the clientside model will stay at 0,0,0 angle at all given times, giving the illusion that the model is sometimes "sticking out".

This solves a issue I considered to be more annoying. Players without permissions can go around "touching" scalable entities, which will make the clientside desyncronize and give the appearance that the entity was unfrozen, despite it's still where it was. This can only be solved when either the owner touches the entity again or just respawns it.

Although I **DO** want to fix this, I haven't found a proper way to do so.

**Comment by CheezusChrust** [comment]
Custom props made through StarfallEx's prop.createCustom function don't seem to have this problem, maybe there's some info you could get from here?
https://github.com/thegrb93/StarfallEx/tree/master/lua/entities/starfall_prop

**Comment by TwistedTail** [comment]
As of 92b53e1, crates shouldn't have any weird issues when it comes to clientside interactions.
