### ISSUE TITLE
[BUG] Refills override acfActive()

### ISSUE THREAD

**Issue by Uberdude9001** [Stooberton/ACF-3#87]
Refills activate crates if disabled with acfActive()

**How to Reproduce**

1. Link gun to crate
2. Fire off a few rounds
3. Disable crate
4. Refill crate

The crate will now be activated.

**Comment by TwistedTail** [comment]
This issue can be also replicated by disabling an ammo crate or fuel tank with the legal checks. Reason behind this is the wire input logic.

When using either wirelinks or ACF wire functions, no actual link is created so therefore there's no source of this, in which case the entity will assume that the input is not wired. Since it assumes it's not wired, it won't even bother with the rest.

**Comment by TwistedTail** [comment]
I believe the best solution for this would be to not mess with ENT.Load on crates when the ammo changes, along with not checking if the wire input has a path when reactivating the entity.

**Comment by TwistedTail** [comment]
Fixed on e4d5974.
